export const data = {
  products: [
    {
      _id: "1",
      name: "NBA Lakers Jersey",
      category: "",
      image: "/images/p1.png",
      price: 120,
      brand: "Nike",
      rating: 5,
      numReviews: 122,
      description: "Lebron James No.23",
      countInStock: 100,
    },
    {
      _id: "2",
      name: "NBA Lakers Jersey",
      category: "",
      image: "/images/p1.png",
      price: 120,
      brand: "Nike",
      rating: 5,
      numReviews: 122,
      description: "Lebron James No.23",
      countInStock: 0,
    },
    {
      _id: "3",
      name: "NBA Lakers Jersey",
      category: "",
      image: "/images/p1.png",
      price: 120,
      brand: "Nike",
      rating: 5,
      numReviews: 122,
      description: "Lebron James No.23",
      countInStock: 1,
    },
    {
      _id: "4",
      name: "NBA Lakers Jersey",
      category: "",
      image: "/images/p1.png",
      price: 120,
      brand: "Nike",
      rating: 5,
      numReviews: 122,
      description: "Lebron James No.23",
      countInStock: 10,
    },
  ],
};
